- name: ansible to install boto3 botocore
  ansible.builtin.pip:
    name:
    - PyMySQL
    executable: pip3.9
- name: task for installing mysql
  ansible.builtin.package:
    name: mysql-server
    state: present

- name: Enable and start mysqld service
  ansible.builtin.service:
    name: mysqld
    enabled: yes
    state: started

- name: checking whether root password is set or not
  community.mysql.mysql_info:
    login_user: root
    login_password: "{{mysql_root_password}}"
    login_host: "{{login_host}}"
  ignore_errors: true
  register: mysql_info

- name: checking the error info
  ansible.builtin.debug:
    msg: "{{mysql_info}}"

- name: setting root password
  ansible.builtin.command:
    cmd: "mysql_secure_installation --set-root-pass ExpenseApp@1"
  when: mysql_info.failed is true